[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[registries.mirror]
index = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"


[net]
git-fetch-with-cli = true

[build]
# https://twitter.com/Manjusaka_Lee/status/1769660168890204378
# https://github.com/apache/opendal/issues/3756
# rustflags = ["-C", "force-frame-pointers=yes", "-C", "debuginfo=1"]

